
name: SSH

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: auth
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      shell: bash
      run: |
          mkdir config
          echo "$SSH_KEY" >> id_rsa
          ssh wwwxfr@ks5.pknw1.co.uk -p 69 -i ./id_rsa -C 'ls -l'
 
