# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: auth
      env:
        AUTH: ${{ secrets.AUTH }}
      shell: bash
      run: |
          mkdir config
          echo "$AUTH" >> config/auth.json
          cat config/auth.json

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build
      continue-on-error: true
      env:
        HEADLESS: "True"
      run: |
        mkdir -p static
        nohup python ./app.py&
        curl -L http://127.0.0.1:5000/content
    - name: check
      run: |
        cp -R web/static/assets static/
        cp web/templates/rendered/* static/
        cd static
        tar -zcvf ../static.tgz *
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: static
        path: static.tgz





